---
name: container-release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       include:
         - component: "base-image"
           path: "./base/fedora/"
         - component: "velocity"
           path: "./apps/velocity/"
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=version::${GITHUB_REF##*/}
      - name: Install qemu dependency
        id: qemu
        run: |
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2.9
        with:
         image: minecraft/${{ matrix.component }}
         tags: v${{ steps.prep.outputs.version }} latest
         oci: true
         layers: true
         containerfiles: ${{ matrix.path }}/Dockerfile
         archs: amd64, arm64
      - name: Push
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
         image: ${{ steps.build.outputs.image }}
         tags:  ${{ steps.build.outputs.tags }}
         registry: ghcr.io/${{ github.actor }}
         username: ${{ github.actor }}
         password: ${{ secrets.CR_TOKEN }}
